name: Continuous Deployment

on:
  workflow_dispatch:

env:
  TF_CLI_ARGS: "-no-color"
  TF_INPUT: "false"

jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Set S3 key name
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        echo "S3_KEY=${REPO_NAME}/${{ secrets.AWS_BUCKET_KEY_NAME }}" >> $GITHUB_ENV

    - name: Terraform Init
      id: init
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_REGION: eu-central-1
      run: |
        cd terraform
        terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${S3_KEY}" -backend-config="region=${AWS_REGION}"
      timeout-minutes: 5

    - name: Terraform Plan
      id: plan
      run: |
        cd terraform
        terraform plan -out=tfplan -detailed-exitcode
      env:
        TF_VAR_lambda_artifacts_bucket_name: ${{ vars.AWS_LAMBDA_ARTIFACTS_S3_BUCKET }}
      timeout-minutes: 15
      continue-on-error: true

    - name: Check Plan Status
      if: steps.plan.outcome == 'failure'
      run: |
        echo "Terraform plan failed or timed out. Please check the logs and configuration."
        exit 1

    - name: Terraform Apply
      if: steps.plan.outputs.exitcode == 2
      run: |
        cd terraform
        terraform apply -auto-approve tfplan
      timeout-minutes: 30

    - name: Check Apply Status
      if: steps.plan.outputs.exitcode == 2
      run: |
        if [ ${{ job.status }} == 'failure' ]; then
          echo "Terraform apply failed or timed out. Please check the logs and infrastructure state."
          exit 1
        fi