name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build partitionProcessorLambda
      run: |
        cd src/partitionProcessorLambda
        npm ci
        npm run build
        mkdir -p ../../dist/partitionProcessorLambda
        cp -r node_modules dist/* ../../dist/partitionProcessorLambda/

    - name: Build batchProcessorLambda
      run: |
        cd src/batchProcessorLambda
        npm ci
        npm run build
        mkdir -p ../../dist/batchProcessorLambda
        cp -r node_modules dist/* ../../dist/batchProcessorLambda/

    - name: Package Lambda functions
      run: |
        cd dist
        zip -r partitionProcessorLambda.zip partitionProcessorLambda
        zip -r batchProcessorLambda.zip batchProcessorLambda

    - name: Configure AWS credentials
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: eu-central-1

    - name: Upload Lambda artifacts to S3
      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
      env:
        S3_BUCKET: ${{ vars.AWS_LAMBDA_ARTIFACTS_S3_BUCKET }}
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        aws s3 cp dist/partitionProcessorLambda.zip s3://${S3_BUCKET}/${REPO_NAME}/partitionProcessorLambda.zip
        aws s3 cp dist/batchProcessorLambda.zip s3://${S3_BUCKET}/${REPO_NAME}/batchProcessorLambda.zip

  terraform-ci:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: eu-central-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Set S3 key name
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
        echo "S3_KEY=${REPO_NAME}/${{ secrets.AWS_BUCKET_KEY_NAME }}" >> $GITHUB_ENV
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

    - name: Terraform Init
      id: init
      env:
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_REGION: eu-central-1
      run: |
        cd terraform
        terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${S3_KEY}" -backend-config="region=${AWS_REGION}"

    - name: Terraform Format
      run: |
        cd terraform
        terraform fmt -check

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      env:
        TF_VAR_lambda_artifacts_bucket_name: ${{ vars.AWS_LAMBDA_ARTIFACTS_S3_BUCKET }}
      run: |
        cd terraform
        terraform plan -var="repo_name=${REPO_NAME}"